# Generated by Django 2.2.6 on 2019-10-13 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('mode_code', models.AutoField(primary_key=True, serialize=False)),
                ('daily_hire_rate', models.IntegerField()),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Manufacturer')),
            ],
        ),
    ]
