# Generated by Django 2.2.6 on 2019-10-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address_line_1', models.CharField(max_length=500)),
                ('address_line_2', models.CharField(max_length=500)),
                ('address_line_3', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('other_customer_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('mechanic_id', models.AutoField(primary_key=True, serialize=False)),
                ('mechanic_name', models.CharField(max_length=100)),
                ('other_mechanic_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('license_number', models.AutoField(primary_key=True, serialize=False)),
                ('current_milage', models.CharField(max_length=50)),
                ('engine_size', models.CharField(max_length=50)),
                ('other_car_details', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Model')),
            ],
        ),
    ]
